### ISSUE TITLE
sbctl requires root to run - Arch Linux - Thinkpad T460

### ISSUE THREAD

**Issue by newtonhonk** [Foxboron/sbctl#241] opened 2023-08-27 10:20 UTC
I am very sorry if I am asking something twice here. I'm getting desperate with SecureBoot under ArchLinux.
On my Thinkpad T460 I get the following errors. I have activated Secureboot in setup mode and also deleted the keys in the bios.

**sbctl status**
Installed:	✓ sbctl is installed
Owner GUID:	[MY ID]
Setup Mode:	✗ Enabled
Secure Boot:	✗ Disabled
Vendor Keys:	none

**sbctl enroll-keys -m:**
Enrolling keys to EFI variables...
With vendor keys from microsoft...✗ 
sbctl requires root to run: couldn't sync keys: couldn't write efi variable: write /sys/firmware/efi/efivars/PK-8be4df61-93ca-11d2-aa0d-00e098032b8c: permission denied

Thanks!

**Comment by Foxboron** [comment] 2023-08-27 14:00
Duplicate of https://github.com/Foxboron/sbctl/issues/171

**Closed by Foxboron** 2023-08-27 14:00 UTC
