### ISSUE TITLE
Panic when signing memtest86+-efi 

### ISSUE THREAD

**Issue by hexchain** [Foxboron/sbctl#196] opened 2023-02-04 07:09 UTC
sbctl 0.10 panics while signing the EFI binary from memtest86+-efi:

```
% sudo sbctl sign /boot/memtest86+/memtest.efi
panic: runtime error: slice bounds out of range [298:258]

goroutine 1 [running]:
github.com/foxboron/go-uefi/efi/pecoff.PECOFFChecksum({0xc000348000, 0x23400, 0x23401})
        github.com/foxboron/go-uefi@v0.0.0-20221211185831-8b4d22f6813c/efi/pecoff/checksum.go:66 +0x6a5
github.com/foxboron/sbctl.SignFile({0xc000022750, 0x24}, {0xc000022780, 0x24}, {0x7ffe476b6561, 0x1c}, {0x7ffe476b6561, 0x1c}, {0x0, 0x0})
        github.com/foxboron/sbctl/keys.go:201 +0x3b8
github.com/foxboron/sbctl.Sign({0x7ffe476b6561?, 0x55d1d2938185?}, {0x7ffe476b6561, 0x1c}, 0x0)
        github.com/foxboron/sbctl/sbctl.go:138 +0x26c
main.glob..func8(0x55d1d2caeac0?, {0xc000071350?, 0x1?, 0x1?})
        github.com/foxboron/sbctl/cmd/sbctl/sign.go:41 +0x1b5
github.com/spf13/cobra.(*Command).execute(0x55d1d2caeac0, {0xc000071320, 0x1, 0x1})
        github.com/spf13/cobra@v1.1.3/command.go:852 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x55d1d2cadbc0)
        github.com/spf13/cobra@v1.1.3/command.go:960 +0x39d
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
        github.com/foxboron/sbctl/cmd/sbctl/main.go:88 +0xf1
```

The EFI binary comes from extra/memtest86+-efi 6.01-1.

**Comment by Foxboron** [comment] 2023-02-06 11:07
Duplicate of https://github.com/Foxboron/sbctl/issues/175

**Closed by Foxboron** 2023-02-06 11:07 UTC
