### ISSUE TITLE
`sign-all` no longer updates already signed output files if input files change

### ISSUE THREAD

**Issue by MichaelEischer** [Foxboron/sbctl#354] opened 2024-08-07 20:56 UTC
Since https://github.com/Foxboron/sbctl/commit/71024417a3a585225c0564b290fe068f7002995f, `sign-all` no longer checks whether the input file's contents have changed but only verifies whether the output files are signed.

In my setup, the EFI UKIs are written by mkinitcpio to `/var/lib/mkinitcpio/efi/` and afterwards `sbctl` writes the signed binary to `/efi/EFI/Linux`. The binaries were enrolled using `sbctl sign -s -o /efi/EFI/Linux/archlinux-linux.efi /var/lib/mkinitcpio/efi/archlinux-linux.efi` and `sbctl sign-all` is used to update the signed binaries. However, the latter no longer works since the commit referenced above.

While writing this issue, I've also found further unexpected behavior:
```
$ cd /var/lib/mkinitcpio/efi
$ sbctl sign archlinux-linux-lts-fallback.efi -o missing.efi
sbctl requires root to run: open /efi/EFI/Linux/archlinux-linux-lts-fallback.efi: permission denied
$ sbctl sign archlinux-linux-lts-fallback.efi -o missing.efi --disable-landlock
File has already been signed /var/lib/mkinitcpio/efi/missing.efi
$ ls
archlinux-linux.efi  archlinux-linux-fallback.efi  archlinux-linux-lts.efi  archlinux-linux-lts-fallback.efi
# output was written to /efi/EFI/Linux/archlinux-linux-lts-fallback.efi instead
```

Apparently the CLI parameter is used to configure the landlock sandbox, but the sign command used the output path from the database.

**Comment by Foxboron** [comment] 2024-08-08 18:05
And here I thought I had fixed all the issues :/ thanks!

**Comment by Foxboron** [comment] 2024-08-11 13:57
I can't reproduce this issue.

Are you sure you are running the latest version? `0.15.4`?

Please also give the output of `--debug`

**Comment by vojket** [comment] 2024-08-11 20:00
I've been running into this too, on arch linux running sbctl 0.15.4-1:

In my setup, mkinitcpio creates a UKI at `/boot/arch-linux.efi` and sbctl puts a signed copy at `/efi/EFI/Linux/arch-linux.efi`.
mkinitcpio's sbctl hook has been disabled for this test.


```
$ rm /boot/arch-linux.efi /efi/EFI/Linux/arch-linux.efi

$ mkinitcpio -P
==> Building image from preset: /etc/mkinitcpio.d/linux.preset: 'default'
==> Using default configuration file: '/etc/mkinitcpio.conf'
  -> -k /boot/vmlinuz-linux -U /boot/arch-linux.efi -g /boot/initramfs-linux.img
...
==> Creating unified kernel image: '/boot/arch-linux.efi'
  -> Using cmdline file: '/etc/kernel/cmdline'
==> Unified kernel image generation successful
...

$ sha256sum /boot/arch-linux.efi
744a1be37b0239753d06b8907e00f5da8a6a01c929b4258c9185c7268848cfa7  /boot/arch-linux.efi

$ sbctl sign --debug /boot/arch-linux.efi -o /efi/EFI/Linux/arch-linux.efi
time=2024-08-11T12:47:07.687-07:00 level=DEBUG msg=landlock rule="REQUIRE {execute,read_file,read_dir} for paths [/sys/devices/virtual/dmi/id/]"
time=2024-08-11T12:47:07.687-07:00 level=DEBUG msg=landlock rule="REQUIRE {execute,write_file,read_file,read_dir,remove_dir,remove_file,make_char,make_dir,make_reg,make_sock,make_fifo,make_block,make_sym,truncate} for paths [/var/lib/sbctl /sys/firmware/efi/efivars/]"
time=2024-08-11T12:47:07.687-07:00 level=DEBUG msg=landlock rule="REQUIRE {execute,read_file} for paths [/sys/kernel/security/tpm0/binary_bios_measurements /etc/localtime]"
time=2024-08-11T12:47:07.687-07:00 level=DEBUG msg=landlock rule="REQUIRE {execute,write_file,read_file} for paths [/var/lib/sbctl/GUID /var/lib/sbctl/files.json /var/lib/sbctl/bundles.json /dev/tpm0 /dev/tpmrm0]"
time=2024-08-11T12:47:07.687-07:00 level=DEBUG msg=landlock rule="REQUIRE {execute,read_file} for paths [/boot/arch-linux.efi]"
time=2024-08-11T12:47:07.687-07:00 level=DEBUG msg=landlock rule="REQUIRE {execute,write_file,read_file,read_dir,remove_dir,remove_file,make_char,make_dir,make_reg,make_sock,make_fifo,make_block,make_sym,truncate} for paths [/efi/EFI/Linux]"
✓ Signed /efi/EFI/Linux/arch-linux.efi

$ sha256sum /efi/EFI/Linux/arch-linux.efi
9697c3cacfdeb1f06e841e73c4d4da1cfab4d4d24efe7d6f0fcb2612e5c6a5bf  /efi/EFI/Linux/arch-linux.efi

$ vim /etc/kernel/cmdline
(add quiet to generate different UKI)

$ mkinitcpio -P
==> Building image from preset: /etc/mkinitcpio.d/linux.preset: 'default'
==> Using default configuration file: '/etc/mkinitcpio.conf'
  -> -k /boot/vmlinuz-linux -U /boot/arch-linux.efi -g /boot/initramfs-linux.img
...
==> Creating unified kernel image: '/boot/arch-linux.efi'
  -> Using cmdline file: '/etc/kernel/cmdline'
==> Unified kernel image generation successful
...

$ sha256sum /boot/arch-linux.efi
d946c0dbcc6cf4926c11f7c628cf455eae5ae369be7fedf94d6a489cbb6a6eb4  /boot/arch-linux.efi

$ sbctl sign /boot/arch-linux.efi -o "/efi/EFI/Linux/arch-linux.efi"
time=2024-08-11T12:48:46.790-07:00 level=DEBUG msg=landlock rule="REQUIRE {execute,read_file,read_dir} for paths [/sys/devices/virtual/dmi/id/]"
time=2024-08-11T12:48:46.790-07:00 level=DEBUG msg=landlock rule="REQUIRE {execute,write_file,read_file,read_dir,remove_dir,remove_file,make_char,make_dir,make_reg,make_sock,make_fifo,make_block,make_sym,truncate} for paths [/var/lib/sbctl /sys/firmware/efi/efivars/]"
time=2024-08-11T12:48:46.790-07:00 level=DEBUG msg=landlock rule="REQUIRE {execute,read_file} for paths [/sys/kernel/security/tpm0/binary_bios_measurements /etc/localtime]"
time=2024-08-11T12:48:46.790-07:00 level=DEBUG msg=landlock rule="REQUIRE {execute,write_file,read_file} for paths [/var/lib/sbctl/GUID /var/lib/sbctl/files.json /var/lib/sbctl/bundles.json /dev/tpm0 /dev/tpmrm0]"
time=2024-08-11T12:48:46.790-07:00 level=DEBUG msg=landlock rule="REQUIRE {execute,read_file} for paths [/boot/arch-linux.efi]"
time=2024-08-11T12:48:46.790-07:00 level=DEBUG msg=landlock rule="REQUIRE {execute,write_file,read_file,truncate} for paths [/efi/EFI/Linux/arch-linux.efi]"
File has already been signed /efi/EFI/Linux/arch-linux.efi

$ sha256sum /efi/EFI/Linux/arch-linux.efi
9697c3cacfdeb1f06e841e73c4d4da1cfab4d4d24efe7d6f0fcb2612e5c6a5bf  /efi/EFI/Linux/arch-linux.efi
```

**Comment by vojket** [comment] 2024-08-12 17:34
Apologies for the confusion. The issue is that sbctl would be expected to resign the UKI after it changes, e.g. for a kernel update. In this test, it simply looks at the output file, sees it's already signed, and thinks it is done. This means that while using the `-o` option, sbctl will never update the signed UKI.
I would expect it to either compare mtimes or keep a checksum of the source file (which seems to have changed in commit [7102441](https://github.com/Foxboron/sbctl/commit/71024417a3a585225c0564b290fe068f7002995f)), so that modifying the UKI and rerunning sbctl generates a matching signed binary.

**Comment by Foxboron** [comment] 2024-08-12 17:43
Ah, sorry. I'm conflating the fact the two issue descriptions in the main post.

**Comment by Foxboron** [comment] 2024-08-12 18:41
Please test this change https://github.com/Foxboron/sbctl/pull/360

**Comment by vojket** [comment] 2024-08-12 23:07
That seems to work correctly on my system, thank you!

**Comment by MichaelEischer** [comment] 2024-08-13 17:20
> Are you sure you are running the latest version? `0.15.4`?

I'm using `sbctl 0.15.4-1` from Arch.

> Please also give the output of `--debug`

```
$ cd /var/lib/mkinitcpio/efi
# copy some unsigned UKI to `test.efi`
$ sbctl sign -s -o /efi/EFI/Linux/test.efi test.efi
$ sbctl list-files # check that test.efi is listed
$ sbctl --debug sign test.efi -o missing.efi
time=2024-08-13T19:12:24.785+02:00 level=DEBUG msg=landlock rule="REQUIRE {execute,read_file,read_dir} for paths [/sys/devices/virtual/dmi/id/]"
time=2024-08-13T19:12:24.785+02:00 level=DEBUG msg=landlock rule="REQUIRE {execute,write_file,read_file,read_dir,remove_dir,remove_file,make_char,make_dir,make_reg,make_sock,make_fifo,make_block,make_sym,truncate} for paths [/var/lib/sbctl /sys/firmware/efi/efivars/]"
time=2024-08-13T19:12:24.785+02:00 level=DEBUG msg=landlock rule="REQUIRE {execute,read_file} for paths [/sys/kernel/security/tpm0/binary_bios_measurements /etc/localtime]"
time=2024-08-13T19:12:24.785+02:00 level=DEBUG msg=landlock rule="REQUIRE {execute,write_file,read_file} for paths [/var/lib/sbctl/GUID /var/lib/sbctl/files.json /var/lib/sbctl/bundles.json /dev/tpm0 /dev/tpmrm0]"
time=2024-08-13T19:12:24.785+02:00 level=DEBUG msg=landlock rule="REQUIRE {execute,read_file} for paths [/var/lib/mkinitcpio/efi/test.efi]"
time=2024-08-13T19:12:24.785+02:00 level=DEBUG msg=landlock rule="REQUIRE {execute,write_file,read_file,read_dir,remove_dir,remove_file,make_char,make_dir,make_reg,make_sock,make_fifo,make_block,make_sym,truncate} for paths [/var/lib/mkinitcpio/efi]"
sbctl requires root to run: open /efi/EFI/Linux/test.efi: permission denied
```

> Please test this change #360

That fixes the resigning issue.

**Comment by Foxboron** [comment] 2024-08-13 19:47
@MichaelEischer This fixes your issue. https://github.com/Foxboron/sbctl/pull/360/commits/065e912de1a5e4358d9e4246e3438031b7f493e8

It turns out that `sbctl` never *actually* checked to see if the output file matches the saved entry in the database. So if `test.efi` is enrolled into sbctl with `/efi/EFI/Linux/test.efi` as output path, then we won't write to `/var/lib/mkinitcpio/efi/missing.efi` regardless.

**Comment by MichaelEischer** [comment] 2024-08-14 20:45
> This fixes your issue. [065e912](https://github.com/Foxboron/sbctl/commit/065e912de1a5e4358d9e4246e3438031b7f493e8)

I've tested it and it seems to work. Thanks!

(P.S.: The commit still contains a stray `fmt.Println`)

**Comment by Foxboron** [comment] 2024-08-14 22:20
> (P.S.: The commit still contains a stray fmt.Println)

Woops, yes it does :) Thanks! I'm 60% sure I'd have caught it before I merged :p

**Closed** 2024-08-16 20:17 UTC
