### ISSUE TITLE
requires root to run error

### ISSUE THREAD

**Issue by sadanslargehole** [Foxboron/sbctl#240] opened 2023-08-19 01:45 UTC
Hello! i am getting this error when i try to run 
```bash
sbctl enroll-keys -m
```
sbctl requires root to run: couldn't sync keys: couldn't write efi variable: write /sys/firmware/efi/efivars/db-d719b2cb-3d3a-4596-a3bc-dad00e67656f: permission denied

i am root
i am using an HP Laptop 15-ef2xxx on debian 12 running linux kernel 6.1.0-11-amd64

**Comment by TheHolyTachanka** [comment] 2023-08-23 10:25
same error for me, on my thinkpad L560

**Comment by sadanslargehole** [comment] 2023-08-23 18:30
let me know if you find an answer

**Comment by Foxboron** [comment] 2023-08-27 14:00
Duplicate of https://github.com/Foxboron/sbctl/issues/171

**Closed by Foxboron** 2023-08-27 14:00 UTC
